### ISSUE TITLE
Feedback do Projeto

### ISSUE THREAD

**Issue by jordyalcides** [chseidler/desempenho-jogadores-gremio#1]
1. Não fez commit todo dia
2. README não fala sobre o build do projeto ou como utilizar
3. Sugestão de correções:
	1. Padronizar o tamanho dos cards, estão diferentes entre si no desktop;
	2. Mostrar a mesma quantidade de cards em todas as linhas no desktop;
	
Qualquer dúvida estou a disposição no discord da comunidade!

**Comment by chseidler** [comment]
Corrigido conforme recomendações.
